// Liste des principales villes françaises pour le formulaire de checkout
export const FRENCH_CITIES = [
  // Villes principales par ordre alphabétique
  "Aix-en-Provence",
  "Ajaccio",
  "Amiens",
  "Angers",
  "Annecy",
  "Antibes",
  "Argenteuil",
  "Asnières-sur-Seine",
  "Avignon",
  "Besançon",
  "Béziers",
  "Bordeaux",
  "Boulogne-Billancourt",
  "Brest",
  "Caen",
  "Cannes",
  "Clermont-Ferrand",
  "Colmar",
  "Cergy",
  "Dijon",
  "Dunkerque",
  "Grenoble",
  "Le Havre",
  "Le Mans",
  "Lille",
  "Limoges",
  "Lyon",
  "Marseille",
  "Metz",
  "Montauban",
  "Montpellier",
  "Mulhouse",
  "Nancy",
  "Nantes",
  "Nice",
  "Nîmes",
  "Orléans",
  "Paris",
  "Pau",
  "Perpignan",
  "Reims",
  "Rennes",
  "Roubaix",
  "Rouen",
  "Saint-Denis",
  "Saint-Étienne",
  "Saint-Paul",
  "Strasbourg",
  "Toulon",
  "Toulouse",
  "Tours",
  "Versailles",
  "Villeurbanne",
  
  // Autres villes importantes
  "Albi",
  "Alès",
  "Amiens",
  "Angoulême",
  "Annecy",
  "Argenteuil",
  "Arras",
  "Aubagne",
  "Aulnay-sous-Bois",
  "Bagnolet",
  "Bastia",
  "Bayonne",
  "Belfort",
  "Blagnac",
  "Blois",
  "Bobigny",
  "Bondy",
  "Bourges",
  "Béziers",
  "Calais",
  "Cannes",
  "Chalon-sur-Saône",
  "Chambéry",
  "Chartres",
  "Châteauroux",
  "Chelles",
  "Cherbourg",
  "Cholet",
  "Clichy",
  "Colomiers",
  "Colombes",
  "Courbevoie",
  "Créteil",
  "Dreux",
  "Drancy",
  "Évry",
  "Fontenay-aux-Roses",
  "Garges-lès-Gonesse",
  "La Courneuve",
  "La Roche-sur-Yon",
  "Levallois-Perret",
  "Lorient",
  "Mantes-la-Jolie",
  "Marignane",
  "Massy",
  "Meaux",
  "Melun",
  "Mérignac",
  "Metz",
  "Mont-de-Marsan",
  "Montfermeil",
  "Montigny-le-Bretonneux",
  "Moulins",
  "Nanterre",
  "Narbonne",
  "Neuilly-sur-Seine",
  "Noisy-le-Grand",
  "Pantin",
  "Périgueux",
  "Pessac",
  "Poitiers",
  "Quimper",
  "Rezé",
  "Rosny-sous-Bois",
  "Roubaix",
  "Saint-Cloud",
  "Saint-Denis",
  "Saint-Étienne",
  "Saint-Herblain",
  "Saint-Maur-des-Fossés",
  "Saint-Nazaire",
  "Saint-Quentin",
  "Sarcelles",
  "Sartrouville",
  "Savigny-sur-Orge",
  "Schiltigheim",
  "Sevran",
  "Strasbourg",
  "Suresnes",
  "Thonon-les-Bains",
  "Troyes",
  "Valence",
  "Vénissieux",
  "Vincennes",
  "Vitrolles", 
  "Vitry-sur-Seine"
];

// Fonction pour filtrer les villes
export const filterCities = (searchTerm: string): string[] => {
  if (!searchTerm || searchTerm.length < 2) return [];
  
  return FRENCH_CITIES.filter(city =>
    city.toLowerCase().includes(searchTerm.toLowerCase())
  ).slice(0, 20); // Limiter à 20 résultats pour la performance
};
